name: Performance Benchmark

on: [push, pull_request]

jobs:
    benchmark:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run benchmarks
              run: ./run_benchmarks.sh

            - name: Upload results
              uses: actions/upload-artifact@v2
              with:
                  name: benchmark-results
                  path: ./benchmark_results.csv
